/**
 * Mapeamento de nome de seleção (PT-BR) → código ISO 3166-1 alpha-2
 * Usado para buscar bandeiras em flagcdn.com
 */
export const TEAM_CODES: Record<string, string> = {
  // América do Sul
  'Brasil': 'br',
  'Argentina': 'ar',
  'Colômbia': 'co',
  'Uruguai': 'uy',
  'Equador': 'ec',
  'Chile': 'cl',
  'Peru': 'pe',
  'Bolívia': 'bo',
  'Paraguai': 'py',
  'Venezuela': 've',

  // América do Norte / CONCACAF
  'EUA': 'us',
  'Canadá': 'ca',
  'México': 'mx',
  'Costa Rica': 'cr',
  'Panamá': 'pa',
  'Honduras': 'hn',
  'Jamaica': 'jm',
  'El Salvador': 'sv',
  'Guatemala': 'gt',
  'Haiti': 'ht',
  'Trinidad e Tobago': 'tt',
  'Curaçao': 'cw',

  // Europa
  'França': 'fr',
  'Alemanha': 'de',
  'Espanha': 'es',
  'Portugal': 'pt',
  'Inglaterra': 'gb-eng',
  'Itália': 'it',
  'Holanda': 'nl',
  'Bélgica': 'be',
  'Croácia': 'hr',
  'Suíça': 'ch',
  'Polônia': 'pl',
  'Sérvia': 'rs',
  'Dinamarca': 'dk',
  'Áustria': 'at',
  'Turquia': 'tr',
  'Ucrânia': 'ua',
  'Hungria': 'hu',
  'Romênia': 'ro',
  'Eslovênia': 'si',
  'Eslováquia': 'sk',
  'República Checa': 'cz',
  'Albânia': 'al',
  'Escócia': 'gb-sct',
  'País de Gales': 'gb-wls',
  'Irlanda': 'ie',
  'Islândia': 'is',
  'Noruega': 'no',
  'Suécia': 'se',
  'Finlândia': 'fi',
  'Grécia': 'gr',
  'Bulgária': 'bg',
  'Geórgia': 'ge',
  'Armênia': 'am',
  'Azerbaijão': 'az',
  'Cazaquistão': 'kz',
  'Bósnia': 'ba',
  'Kosovo': 'xk',
  'Montenegro': 'me',
  'Macedônia do Norte': 'mk',
  'Luxemburgo': 'lu',
  'Ilhas Faroe': 'fo',
  'Gibraltar': 'gi',
  'Liechtenstein': 'li',
  'Andorra': 'ad',
  'Malta': 'mt',
  'Chipre': 'cy',
  'Israel': 'il',

  // África
  'Marrocos': 'ma',
  'Senegal': 'sn',
  'Gana': 'gh',
  'Nigéria': 'ng',
  'Costa do Marfim': 'ci',
  'Camarões': 'cm',
  'Mali': 'ml',
  'Egito': 'eg',
  'Argélia': 'dz',
  'Tunísia': 'tn',
  'África do Sul': 'za',
  'Zâmbia': 'zm',
  'Uganda': 'ug',
  'Tanzânia': 'tz',
  'Moçambique': 'mz',
  'Angola': 'ao',
  'Congo': 'cd',
  'Guiné': 'gn',
  'Burkina Faso': 'bf',
  'Cabo Verde': 'cv',
  'Benin': 'bj',
  'Etiópia': 'et',
  'Quênia': 'ke',

  // Ásia / Oceania
  'Japão': 'jp',
  'Coreia do Sul': 'kr',
  'Austrália': 'au',
  'Arábia Saudita': 'sa',
  'Irã': 'ir',
  'Iraque': 'iq',
  'Catar': 'qa',
  'Qatar': 'qa',
  'Emirados Árabes': 'ae',
  'Jordânia': 'jo',
  'Omã': 'om',
  'Kuwait': 'kw',
  'Bahrein': 'bh',
  'China': 'cn',
  'Coreia do Norte': 'kp',
  'Tailândia': 'th',
  'Vietnã': 'vn',
  'Indonésia': 'id',
  'Malásia': 'my',
  'Índia': 'in',
  'Uzbequistão': 'uz',
  'Quirguistão': 'kg',
  'Tadjiquistão': 'tj',
  'Síria': 'sy',
  'Líbano': 'lb',
  'Palestina': 'ps',
  'Nova Zelândia': 'nz',
  'Filipinas': 'ph',
  'Singapura': 'sg',
  'Hong Kong': 'hk',
  'Taiwan': 'tw',
}

export function getCountryCode(teamName: string): string | null {
  return TEAM_CODES[teamName] ?? null
}

export function getFlagUrl(teamName: string, width: 40 | 80 | 160 = 80): string | null {
  const code = getCountryCode(teamName)
  if (!code) return null
  return `https://flagcdn.com/w${width}/${code}.png`
}
